package com.moneywizzard.dao.impl;

import java.util.List;

import org.hibernate.Criteria;
import org.hibernate.HibernateException;
import org.hibernate.criterion.Restrictions;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import com.moneywizzard.dao.BudgetDao;
import com.moneywizzard.model.Budget;
import com.moneywizzard.model.Expenses;

/**
 * DAO for table: Budget.
 * @author autogenerated
 */
@Repository
public class BudgetDaoImpl extends GenericHibernateDaoImpl<Budget, String> implements BudgetDao {
	
	/** Constructor method. */
		public BudgetDaoImpl() {
			super(Budget.class);
		}
		
		@Override
		@Transactional(readOnly = true, propagation = Propagation.REQUIRED)
		public List<Budget> getByCriteria(Budget budget) throws Exception{

			List<Budget> budgets = null;
			try {
				Criteria crit = getSession().createCriteria(getPersistentClass());

				if(budget.getPersonid()!=null){
					crit.add(Restrictions.eq("personid", budget.getPersonid()));
				}
				
				if(budget.getYear()!=null){
					crit.add(Restrictions.eq("year", budget.getYear()));
				}
				
				if(budget.getMonth()!=null){
					crit.add(Restrictions.eq("month", budget.getMonth()));
				}

				budgets = crit.list();
				return budgets;

			} catch (HibernateException e) {
				throw e;
			}	

		}
	}

