package com.moneywizzard.dao.impl;

import org.springframework.stereotype.Repository;

import com.moneywizzard.dao.ExpensecategoryDao;
import com.moneywizzard.model.Expensecategory;
 
 
/**
 * DAO for table: Expensecategory.
 * @author autogenerated
 */
@Repository
public class ExpensecategoryDaoImpl extends GenericHibernateDaoImpl<Expensecategory, String> implements ExpensecategoryDao {
	
	/** Constructor method. */
		public ExpensecategoryDaoImpl() {
			super(Expensecategory.class);
		}
	}

