package com.moneywizzard.dao.impl;

import java.util.List;

import org.hibernate.Criteria;
import org.hibernate.HibernateException;
import org.hibernate.criterion.Restrictions;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import com.moneywizzard.dao.ExpensesDao;
import com.moneywizzard.model.Expenses;
import com.moneywizzard.model.Person;
import com.moneywizzard.utils.MWUtils;
 
 
/**
 * DAO for table: Expenses.
 * @author autogenerated
 */
@Repository
public class ExpensesDaoImpl extends GenericHibernateDaoImpl<Expenses, String> implements ExpensesDao {
	
	/** Constructor method. */
		public ExpensesDaoImpl() {
			super(Expenses.class);
		}
		
		@Override
		@Transactional(readOnly = true, propagation = Propagation.REQUIRED)
		public List<Expenses> getByCriteria(Expenses expense) throws Exception{

			List<Expenses> expenses = null;
			try {
				Criteria crit = getSession().createCriteria(getPersistentClass());

				if(expense.getPersonid()!=null){
					crit.add(Restrictions.eq("personid", expense.getPersonid()));
				}

				crit.setResultTransformer(Criteria.DISTINCT_ROOT_ENTITY);
				expenses = crit.list();
				return expenses;

			} catch (HibernateException e) {
				throw e;
			}	

		}
	}

