package com.moneywizzard.dao.impl;

import java.io.Serializable;

import org.springframework.stereotype.Repository;

import com.moneywizzard.dao.FriendsPKDao;
import com.moneywizzard.model.FriendsPK;
 
/**
 * DAO for table: FriendsPK.
 * @author autogenerated
 */
@Repository
public class FriendsPKDaoImpl extends GenericHibernateDaoImpl<FriendsPK, Serializable> implements FriendsPKDao {
	
	/** Constructor method. */
		public FriendsPKDaoImpl() {
			super(FriendsPK.class);
		}
	}

