package com.moneywizzard.dao.impl;

import java.util.List;

import org.hibernate.Criteria;
import org.hibernate.HibernateException;
import org.hibernate.criterion.Restrictions;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import com.moneywizzard.dao.GroupexpenseDao;
import com.moneywizzard.model.Budget;
import com.moneywizzard.model.Groupexpense;
 
 
/**
 * DAO for table: Groupexpense.
 * @author autogenerated
 */
@Repository
public class GroupexpenseDaoImpl extends GenericHibernateDaoImpl<Groupexpense, String> implements GroupexpenseDao {
	
	/** Constructor method. */
		public GroupexpenseDaoImpl() {
			super(Groupexpense.class);
		}
		
		@Override
		@Transactional(readOnly = true, propagation = Propagation.REQUIRED)
		public List<Groupexpense> getByCriteria(Groupexpense groupexpense) throws Exception{

			List<Groupexpense> groupexpenses = null;
			try {
				Criteria crit = getSession().createCriteria(getPersistentClass());

				if(groupexpense.getPaidbypersonid()!=null){
					crit.add(Restrictions.eq("paidbypersonid", groupexpense.getPaidbypersonid()));
				}
				if(groupexpense.getGroupid()!=null){
					crit.add(Restrictions.eq("groupid", groupexpense.getGroupid()));
				}
				
				crit.setResultTransformer(Criteria.DISTINCT_ROOT_ENTITY);
				groupexpenses = crit.list();
				return groupexpenses;

			} catch (HibernateException e) {
				throw e;
			}	

		}
	}

