package com.moneywizzard.dao.impl;

import org.springframework.stereotype.Repository;

import com.moneywizzard.dao.GroupDao;
import com.moneywizzard.model.Group;
 
 
/**
 * DAO for table: Group.
 * @author autogenerated
 */
@Repository
public class GroupDaoImpl extends GenericHibernateDaoImpl<Group, String> implements GroupDao {
	
	/** Constructor method. */
		public GroupDaoImpl() {
			super(Group.class);
		}
	}

