package com.moneywizzard.dao.impl;

import java.util.List;

import org.hibernate.Criteria;
import org.hibernate.HibernateException;
import org.hibernate.criterion.Restrictions;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import com.moneywizzard.dao.GroupmappingDao;
import com.moneywizzard.model.Groupmapping;
import com.moneywizzard.model.GroupmappingPK;
import com.moneywizzard.model.Person;
import com.moneywizzard.utils.MWUtils;
 
/**
 * DAO for table: Groupmapping.
 * @author autogenerated
 */
@Repository
public class GroupmappingDaoImpl extends GenericHibernateDaoImpl<Groupmapping, GroupmappingPK> implements GroupmappingDao {
	
	/** Constructor method. */
		public GroupmappingDaoImpl() {
			super(Groupmapping.class);
		}
		
		@Override
		@Transactional(readOnly = true, propagation = Propagation.REQUIRED)
		public List<Groupmapping> getByCriteria(Groupmapping groupmapping) throws Exception{

			try {
				Criteria crit = getSession().createCriteria(getPersistentClass());

				if(groupmapping.getId()!=null && groupmapping.getId().getPersonid()!=null){
					crit.add(Restrictions.eq("id.personid", groupmapping.getId().getPersonid()));
				}
				if(groupmapping.getId()!=null && groupmapping.getId().getGroupid()!=null){
					crit.add(Restrictions.eq("id.groupid", groupmapping.getId().getGroupid()));
				}

				return crit.list();

			} catch (HibernateException e) {
				throw e;
			}	

		}
	}

