package com.moneywizzard.dao.impl;

import java.io.Serializable;

import org.springframework.stereotype.Repository;

import com.moneywizzard.dao.GroupmappingPKDao;
import com.moneywizzard.model.GroupmappingPK;
 
/**
 * DAO for table: GroupmappingPK.
 * @author autogenerated
 */
@Repository
public class GroupmappingPKDaoImpl extends GenericHibernateDaoImpl<GroupmappingPK, Serializable> implements GroupmappingPKDao {
	
	/** Constructor method. */
		public GroupmappingPKDaoImpl() {
			super(GroupmappingPK.class);
		}
	}

