package com.moneywizzard.dao.impl;

import org.hibernate.Criteria;
import org.hibernate.HibernateException;
import org.hibernate.criterion.Restrictions;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import com.moneywizzard.dao.MoneywizardaccountDao;
import com.moneywizzard.model.Moneywizardaccount;
import com.moneywizzard.model.Person;
 
 
/**
 * DAO for table: Moneywizardaccount.
 * @author autogenerated
 */
@Repository
public class MoneywizardaccountDaoImpl extends GenericHibernateDaoImpl<Moneywizardaccount, String> implements MoneywizardaccountDao {
	
	/** Constructor method. */
		public MoneywizardaccountDaoImpl() {
			super(Moneywizardaccount.class);
		}
		
		 @Override
		    @Transactional(readOnly = true, propagation = Propagation.REQUIRED)
		    public Moneywizardaccount getByCriteria(Person person) {
		        try {
		            
		            Criteria crit = getSession().createCriteria(getPersistentClass());

		            if (person!=null) {
		                crit.add(Restrictions.eq("personid",   person ));
		            }

		            if(crit.list()!=null && crit.list().size()>0){
			            return (Moneywizardaccount) crit.list().get(0);		            	
		            }else{
		            	return null;
		            }

		        } catch (HibernateException e) {
		            throw e;
		        }

		    }
	}

