package com.moneywizzard.model.iface;

import com.moneywizzard.model.Person;

/** 
 * Object interface mapping for hibernate-handled table: budget.
 * @author autogenerated
 */

public interface IBudget {



    /**
     * Return the value associated with the column: amount.
	 * @return A Double object (this.amount)
	 */
	Double getAmount();
	

  
    /**  
     * Set the value related to the column: amount.
	 * @param amount the amount value you wish to set
	 */
	void setAmount(final Double amount);

    /**
     * Return the value associated with the column: id.
	 * @return A String object (this.id)
	 */
	String getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final String id);

    /**
     * Return the value associated with the column: month.
	 * @return A Integer object (this.month)
	 */
	Integer getMonth();
	

  
    /**  
     * Set the value related to the column: month.
	 * @param month the month value you wish to set
	 */
	void setMonth(final Integer month);

    /**
     * Return the value associated with the column: personid.
	 * @return A Person object (this.personid)
	 */
	Person getPersonid();
	

  
    /**  
     * Set the value related to the column: personid.
	 * @param personid the personid value you wish to set
	 */
	void setPersonid(final Person personid);

    /**
     * Return the value associated with the column: year.
	 * @return A Integer object (this.year)
	 */
	Integer getYear();
	

  
    /**  
     * Set the value related to the column: year.
	 * @param year the year value you wish to set
	 */
	void setYear(final Integer year);

	// end of interface
}