package com.moneywizzard.model.iface;
import java.util.Set;

import com.moneywizzard.model.Expenses;


/** 
 * Object interface mapping for hibernate-handled table: expensecategory.
 * @author autogenerated
 */

public interface IExpensecategory {



    /**
     * Return the value associated with the column: categoryname.
	 * @return A String object (this.categoryname)
	 */
	String getCategoryname();
	

  
    /**  
     * Set the value related to the column: categoryname.
	 * @param categoryname the categoryname value you wish to set
	 */
	void setCategoryname(final String categoryname);

    /**
     * Return the value associated with the column: expenses.
	 * @return A Set&lt;Expenses&gt; object (this.expenses)
	 */
	Set<Expenses> getExpenseses();
	
	/**
	 * Adds a bi-directional link of type Expenses to the expenseses set.
	 * @param expenses item to add
	 */
	void addExpenses(Expenses expenses);

  
    /**  
     * Set the value related to the column: expenses.
	 * @param expenses the expenses value you wish to set
	 */
	void setExpenseses(final Set<Expenses> expenses);

    /**
     * Return the value associated with the column: id.
	 * @return A String object (this.id)
	 */
	String getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final String id);

	// end of interface
}