package com.moneywizzard.model.iface;
import com.moneywizzard.model.FriendsPK;


/** 
 * Object interface mapping for hibernate-handled table: friends.
 * @author autogenerated
 */

public interface IFriends {



    /**
     * Return the value associated with the column: id.
	 * @return A FriendsPK object (this.id)
	 */
	FriendsPK getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final FriendsPK id);

	// end of interface
}