package com.moneywizzard.model.iface;
import com.moneywizzard.model.Person;


/** 
 * Object interface mapping for hibernate-handled table: friends.
 * @author autogenerated
 */

public interface IFriendsPK {



    /**
     * Return the value associated with the column: friendid.
	 * @return A Person object (this.friendid)
	 */
	Person getFriendid();
	

  
    /**  
     * Set the value related to the column: friendid.
	 * @param friendid the friendid value you wish to set
	 */
	void setFriendid(final Person friendid);

    /**
     * Return the value associated with the column: personid.
	 * @return A Person object (this.personid)
	 */
	Person getPersonid();
	

  
    /**  
     * Set the value related to the column: personid.
	 * @param personid the personid value you wish to set
	 */
	void setPersonid(final Person personid);

	// end of interface
}