package com.moneywizzard.model.iface;
import java.util.Set;

import com.moneywizzard.model.Group;
import com.moneywizzard.model.Groupexpensemapping;
import com.moneywizzard.model.Person;


/** 
 * Object interface mapping for hibernate-handled table: groupexpense.
 * @author autogenerated
 */

public interface IGroupexpense {



    /**
     * Return the value associated with the column: amount.
	 * @return A Double object (this.amount)
	 */
	Double getAmount();
	

  
    /**  
     * Set the value related to the column: amount.
	 * @param amount the amount value you wish to set
	 */
	void setAmount(final Double amount);

    /**
     * Return the value associated with the column: comment.
	 * @return A String object (this.comment)
	 */
	String getComment();
	

  
    /**  
     * Set the value related to the column: comment.
	 * @param comment the comment value you wish to set
	 */
	void setComment(final String comment);

    /**
     * Return the value associated with the column: groupexpensemapping.
	 * @return A Set&lt;Groupexpensemapping&gt; object (this.groupexpensemapping)
	 */
	Set<Groupexpensemapping> getGroupexpensemappings();
	
	/**
	 * Adds a bi-directional link of type Groupexpensemapping to the groupexpensemappings set.
	 * @param groupexpensemapping item to add
	 */
	void addGroupexpensemapping(Groupexpensemapping groupexpensemapping);

  
    /**  
     * Set the value related to the column: groupexpensemapping.
	 * @param groupexpensemapping the groupexpensemapping value you wish to set
	 */
	void setGroupexpensemappings(final Set<Groupexpensemapping> groupexpensemapping);

    /**
     * Return the value associated with the column: groupid.
	 * @return A Group object (this.groupid)
	 */
	Group getGroupid();
	

  
    /**  
     * Set the value related to the column: groupid.
	 * @param groupid the groupid value you wish to set
	 */
	void setGroupid(final Group groupid);

    /**
     * Return the value associated with the column: id.
	 * @return A String object (this.id)
	 */
	String getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final String id);

    /**
     * Return the value associated with the column: image.
	 * @return A Byte[] object (this.image)
	 */
	Byte[] getImage();
	

  
    /**  
     * Set the value related to the column: image.
	 * @param image the image value you wish to set
	 */
	void setImage(final Byte[] image);

    /**
     * Return the value associated with the column: paidbypersonid.
	 * @return A Person object (this.paidbypersonid)
	 */
	Person getPaidbypersonid();
	

  
    /**  
     * Set the value related to the column: paidbypersonid.
	 * @param paidbypersonid the paidbypersonid value you wish to set
	 */
	void setPaidbypersonid(final Person paidbypersonid);

	// end of interface
}