package com.moneywizzard.model.iface;

import com.moneywizzard.model.GroupmappingPK;

/** 
 * Object interface mapping for hibernate-handled table: groupmapping.
 * @author autogenerated
 */

public interface IGroupmapping {



    /**
     * Return the value associated with the column: id.
	 * @return A GroupmappingPK object (this.id)
	 */
	GroupmappingPK getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final GroupmappingPK id);

	// end of interface
}