package com.moneywizzard.model.iface;
import java.util.Set;

import com.moneywizzard.model.Groupexpense;
import com.moneywizzard.model.Groupmapping;


/** 
 * Object interface mapping for hibernate-handled table: group.
 * @author autogenerated
 */

public interface IGroup {



    /**
     * Return the value associated with the column: groupexpense.
	 * @return A Set&lt;Groupexpense&gt; object (this.groupexpense)
	 */
	Set<Groupexpense> getGroupexpenses();
	
	/**
	 * Adds a bi-directional link of type Groupexpense to the groupexpenses set.
	 * @param groupexpense item to add
	 */
	void addGroupexpense(Groupexpense groupexpense);

  
    /**  
     * Set the value related to the column: groupexpense.
	 * @param groupexpense the groupexpense value you wish to set
	 */
	void setGroupexpenses(final Set<Groupexpense> groupexpense);

    /**
     * Return the value associated with the column: groupmapping.
	 * @return A Set&lt;Groupmapping&gt; object (this.groupmapping)
	 */
	Set<Groupmapping> getGroupmappings();
	
	/**
	 * Adds a bi-directional link of type Groupmapping to the groupmappings set.
	 * @param groupmapping item to add
	 */
	void addGroupmapping(Groupmapping groupmapping);

  
    /**  
     * Set the value related to the column: groupmapping.
	 * @param groupmapping the groupmapping value you wish to set
	 */
	void setGroupmappings(final Set<Groupmapping> groupmapping);

    /**
     * Return the value associated with the column: id.
	 * @return A String object (this.id)
	 */
	String getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final String id);

    /**
     * Return the value associated with the column: image.
	 * @return A Byte[] object (this.image)
	 */
	Byte[] getImage();
	

  
    /**  
     * Set the value related to the column: image.
	 * @param image the image value you wish to set
	 */
	void setImage(final Byte[] image);

    /**
     * Return the value associated with the column: name.
	 * @return A String object (this.name)
	 */
	String getName();
	

  
    /**  
     * Set the value related to the column: name.
	 * @param name the name value you wish to set
	 */
	void setName(final String name);

	// end of interface
}