package com.moneywizzard.model.iface;
import com.moneywizzard.model.Group;
import com.moneywizzard.model.Person;


/** 
 * Object interface mapping for hibernate-handled table: groupmapping.
 * @author autogenerated
 */

public interface IGroupmappingPK {



    /**
     * Return the value associated with the column: groupid.
	 * @return A Group object (this.groupid)
	 */
	Group getGroupid();
	

  
    /**  
     * Set the value related to the column: groupid.
	 * @param groupid the groupid value you wish to set
	 */
	void setGroupid(final Group groupid);

    /**
     * Return the value associated with the column: personid.
	 * @return A Person object (this.personid)
	 */
	Person getPersonid();
	

  
    /**  
     * Set the value related to the column: personid.
	 * @param personid the personid value you wish to set
	 */
	void setPersonid(final Person personid);

	// end of interface
}