package com.moneywizzard.model.iface;
import com.moneywizzard.model.Groupexpense;
import com.moneywizzard.model.Person;


/** 
 * Object interface mapping for hibernate-handled table: groupexpensemapping.
 * @author autogenerated
 */

public interface IGroupexpensemapping {



    /**
     * Return the value associated with the column: amount.
	 * @return A Double object (this.amount)
	 */
	Double getAmount();
	

  
    /**  
     * Set the value related to the column: amount.
	 * @param amount the amount value you wish to set
	 */
	void setAmount(final Double amount);

    /**
     * Return the value associated with the column: groupexpenseid.
	 * @return A Groupexpense object (this.groupexpenseid)
	 */
	Groupexpense getGroupexpenseid();
	

  
    /**  
     * Set the value related to the column: groupexpenseid.
	 * @param groupexpenseid the groupexpenseid value you wish to set
	 */
	void setGroupexpenseid(final Groupexpense groupexpenseid);

    /**
     * Return the value associated with the column: id.
	 * @return A String object (this.id)
	 */
	String getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final String id);

    /**
     * Return the value associated with the column: personid.
	 * @return A Person object (this.personid)
	 */
	Person getPersonid();
	

  
    /**  
     * Set the value related to the column: personid.
	 * @param personid the personid value you wish to set
	 */
	void setPersonid(final Person personid);

	// end of interface
}