package com.moneywizzard.model.iface;
import java.util.Date;

import com.moneywizzard.model.Person;


/** 
 * Object interface mapping for hibernate-handled table: mwaccounthistory.
 * @author autogenerated
 */

public interface IMwaccounthistory {



    /**
     * Return the value associated with the column: amount.
	 * @return A Double object (this.amount)
	 */
	Double getAmount();
	

  
    /**  
     * Set the value related to the column: amount.
	 * @param amount the amount value you wish to set
	 */
	void setAmount(final Double amount);

    /**
     * Return the value associated with the column: date.
	 * @return A Date object (this.date)
	 */
	Date getDate();
	

  
    /**  
     * Set the value related to the column: date.
	 * @param date the date value you wish to set
	 */
	void setDate(final Date date);

    /**
     * Return the value associated with the column: id.
	 * @return A String object (this.id)
	 */
	String getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final String id);

    /**
     * Return the value associated with the column: recieverpersonid.
	 * @return A Person object (this.recieverpersonid)
	 */
	Person getRecieverpersonid();
	

  
    /**  
     * Set the value related to the column: recieverpersonid.
	 * @param recieverpersonid the recieverpersonid value you wish to set
	 */
	void setRecieverpersonid(final Person recieverpersonid);

    /**
     * Return the value associated with the column: senderpersonid.
	 * @return A Person object (this.senderpersonid)
	 */
	Person getSenderpersonid();
	

  
    /**  
     * Set the value related to the column: senderpersonid.
	 * @param senderpersonid the senderpersonid value you wish to set
	 */
	void setSenderpersonid(final Person senderpersonid);

	// end of interface
}