package com.moneywizzard.model.iface;
import java.util.Set;

import com.moneywizzard.model.Budget;
import com.moneywizzard.model.Expenses;
import com.moneywizzard.model.Friends;
import com.moneywizzard.model.Groupexpense;
import com.moneywizzard.model.Groupexpensemapping;
import com.moneywizzard.model.Groupmapping;
import com.moneywizzard.model.Moneywizardaccount;
import com.moneywizzard.model.Mwaccounthistory;


/** 
 * Object interface mapping for hibernate-handled table: person.
 * @author autogenerated
 */

public interface IPerson {



    /**
     * Return the value associated with the column: budget.
	 * @return A Set&lt;Budget&gt; object (this.budget)
	 */
	Set<Budget> getBudgets();
	
	/**
	 * Adds a bi-directional link of type Budget to the budgets set.
	 * @param budget item to add
	 */
	void addBudget(Budget budget);

  
    /**  
     * Set the value related to the column: budget.
	 * @param budget the budget value you wish to set
	 */
	void setBudgets(final Set<Budget> budget);

    /**
     * Return the value associated with the column: emailid.
	 * @return A String object (this.emailid)
	 */
	String getEmailid();
	

  
    /**  
     * Set the value related to the column: emailid.
	 * @param emailid the emailid value you wish to set
	 */
	void setEmailid(final String emailid);

    /**
     * Return the value associated with the column: expenses.
	 * @return A Set&lt;Expenses&gt; object (this.expenses)
	 */
	Set<Expenses> getExpenseses();
	
	/**
	 * Adds a bi-directional link of type Expenses to the expenseses set.
	 * @param expenses item to add
	 */
	void addExpenses(Expenses expenses);

  
    /**  
     * Set the value related to the column: expenses.
	 * @param expenses the expenses value you wish to set
	 */
	void setExpenseses(final Set<Expenses> expenses);

    /**
     * Return the value associated with the column: friends.
	 * @return A Set&lt;Friends&gt; object (this.friends)
	 */
	Set<Friends> getFriendss();
	
	/**
	 * Adds a bi-directional link of type Friends to the friendss set.
	 * @param friends item to add
	 */
	void addFriends(Friends friends);

  
    /**  
     * Set the value related to the column: friends.
	 * @param friends the friends value you wish to set
	 */
	void setFriendss(final Set<Friends> friends);

    /**
     * Return the value associated with the column: groupexpense.
	 * @return A Set&lt;Groupexpense&gt; object (this.groupexpense)
	 */
	Set<Groupexpense> getGroupexpenses();
	
	/**
	 * Adds a bi-directional link of type Groupexpense to the groupexpenses set.
	 * @param groupexpense item to add
	 */
	void addGroupexpense(Groupexpense groupexpense);

  
    /**  
     * Set the value related to the column: groupexpense.
	 * @param groupexpense the groupexpense value you wish to set
	 */
	void setGroupexpenses(final Set<Groupexpense> groupexpense);

    /**
     * Return the value associated with the column: groupexpensemapping.
	 * @return A Set&lt;Groupexpensemapping&gt; object (this.groupexpensemapping)
	 */
	Set<Groupexpensemapping> getGroupexpensemappings();
	
	/**
	 * Adds a bi-directional link of type Groupexpensemapping to the groupexpensemappings set.
	 * @param groupexpensemapping item to add
	 */
	void addGroupexpensemapping(Groupexpensemapping groupexpensemapping);

  
    /**  
     * Set the value related to the column: groupexpensemapping.
	 * @param groupexpensemapping the groupexpensemapping value you wish to set
	 */
	void setGroupexpensemappings(final Set<Groupexpensemapping> groupexpensemapping);

    /**
     * Return the value associated with the column: groupmapping.
	 * @return A Set&lt;Groupmapping&gt; object (this.groupmapping)
	 */
	Set<Groupmapping> getGroupmappings();
	
	/**
	 * Adds a bi-directional link of type Groupmapping to the groupmappings set.
	 * @param groupmapping item to add
	 */
	void addGroupmapping(Groupmapping groupmapping);

  
    /**  
     * Set the value related to the column: groupmapping.
	 * @param groupmapping the groupmapping value you wish to set
	 */
	void setGroupmappings(final Set<Groupmapping> groupmapping);

    /**
     * Return the value associated with the column: id.
	 * @return A String object (this.id)
	 */
	String getId();
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	void setId(final String id);

    /**
     * Return the value associated with the column: moneywizardaccount.
	 * @return A Set&lt;Moneywizardaccount&gt; object (this.moneywizardaccount)
	 */
	Set<Moneywizardaccount> getMoneywizardaccounts();
	
	/**
	 * Adds a bi-directional link of type Moneywizardaccount to the moneywizardaccounts set.
	 * @param moneywizardaccount item to add
	 */
	void addMoneywizardaccount(Moneywizardaccount moneywizardaccount);

  
    /**  
     * Set the value related to the column: moneywizardaccount.
	 * @param moneywizardaccount the moneywizardaccount value you wish to set
	 */
	void setMoneywizardaccounts(final Set<Moneywizardaccount> moneywizardaccount);

    /**
     * Return the value associated with the column: mwaccounthistory.
	 * @return A Set&lt;Mwaccounthistory&gt; object (this.mwaccounthistory)
	 */
	Set<Mwaccounthistory> getMwaccounthistories();
	
	/**
	 * Adds a bi-directional link of type Mwaccounthistory to the mwaccounthistories set.
	 * @param mwaccounthistory item to add
	 */
	void addMwaccounthistory(Mwaccounthistory mwaccounthistory);

  
    /**  
     * Set the value related to the column: mwaccounthistory.
	 * @param mwaccounthistory the mwaccounthistory value you wish to set
	 */
	void setMwaccounthistories(final Set<Mwaccounthistory> mwaccounthistory);

    /**
     * Return the value associated with the column: name.
	 * @return A String object (this.name)
	 */
	String getName();
	

  
    /**  
     * Set the value related to the column: name.
	 * @param name the name value you wish to set
	 */
	void setName(final String name);

    /**
     * Return the value associated with the column: password.
	 * @return A String object (this.password)
	 */
	String getPassword();
	

  
    /**  
     * Set the value related to the column: password.
	 * @param password the password value you wish to set
	 */
	void setPassword(final String password);

    /**
     * Return the value associated with the column: phonenumber.
	 * @return A Integer object (this.phonenumber)
	 */
	Integer getPhonenumber();
	

  
    /**  
     * Set the value related to the column: phonenumber.
	 * @param phonenumber the phonenumber value you wish to set
	 */
	void setPhonenumber(final Integer phonenumber);

    /**
     * Return the value associated with the column: photo.
	 * @return A Byte[] object (this.photo)
	 */
	Byte[] getPhoto();
	

  
    /**  
     * Set the value related to the column: photo.
	 * @param photo the photo value you wish to set
	 */
	void setPhoto(final Byte[] photo);

	// end of interface
}