package com.moneywizzard.model;

import java.io.Serializable;

import javax.persistence.CascadeType;
import javax.persistence.Embeddable;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Transient;

import com.moneywizzard.model.iface.IGroupmappingPK;


/** 
 * Object mapping for hibernate-handled table: groupmapping.
 * @author autogenerated
 */

@Embeddable
public class GroupmappingPK implements Cloneable, Serializable,  IGroupmappingPK {

	/** Serial Version UID. */
	private static final long serialVersionUID = -558953629L;

	

	/** Field mapping. */
	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.EAGER )
	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@JoinColumn(name = "groupId", nullable = false , insertable = false, updatable = false )
	private Group groupid;

	/** Field mapping. */
	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.EAGER )
	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@JoinColumn(name = "personId", nullable = false , insertable = false, updatable = false )
	private Person personid;

 


 
	/** Return the type of this class. Useful for when dealing with proxies.
	* @return Defining class.
	*/
	@Transient
	public Class<?> getClassType() {
		return GroupmappingPK.class;
	}
 

    /**
     * Return the value associated with the column: groupid.
	 * @return A Group object (this.groupid)
	 */
	public Group getGroupid() {
		return this.groupid;
		
	}
	

  
    /**  
     * Set the value related to the column: groupid.
	 * @param groupid the groupid value you wish to set
	 */
	public void setGroupid(final Group groupid) {
		this.groupid = groupid;
	}

    /**
     * Return the value associated with the column: personid.
	 * @return A Person object (this.personid)
	 */
	public Person getPersonid() {
		return this.personid;
		
	}
	

  
    /**  
     * Set the value related to the column: personid.
	 * @param personid the personid value you wish to set
	 */
	public void setPersonid(final Person personid) {
		this.personid = personid;
	}


   /**
    * Deep copy.
	* @return cloned object
	* @throws CloneNotSupportedException on error
    */
    @Override
    public GroupmappingPK clone() throws CloneNotSupportedException {
		
        final GroupmappingPK copy = (GroupmappingPK)super.clone();

		return copy;
	}
	


	/** Provides toString implementation.
	 * @see java.lang.Object#toString()
	 * @return String representation of this class.
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		
		return sb.toString();		
	}


	/** Equals implementation. 
	 * @see java.lang.Object#equals(java.lang.Object)
	 * @param aThat Object to compare with
	 * @return true/false
	 */
	@Override
	public boolean equals(final Object aThat) {
		Object proxyThat = aThat;
		
		if ( this == aThat ) {
			 return true;
		}

		if (aThat == null)  {
			 return false;
		}
		
		final GroupmappingPK that; 
		try {
			that = (GroupmappingPK) proxyThat;
			if ( !(that.getClassType().equals(this.getClassType()))){
				return false;
			}
		} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		} catch (ClassCastException e) {
				return false;
		}
		
		
		boolean result = true;
		result = result && (((getGroupid() == null) && (that.getGroupid() == null)) || (getGroupid() != null && getGroupid().getId().equals(that.getGroupid().getId())));	
		result = result && (((getPersonid() == null) && (that.getPersonid() == null)) || (getPersonid() != null && getPersonid().getId().equals(that.getPersonid().getId())));	
		return result;
	}
	
	/** Calculate the hashcode.
	 * @see java.lang.Object#hashCode()
	 * @return a calculated number
	 */
	@Override
	public int hashCode() {
	int hash = 0;
		hash = hash + getGroupid().hashCode();
		hash = hash + getPersonid().hashCode();
	return hash;
	}
	

	
}
