package com.moneywizzard.model;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.moneywizzard.model.iface.IGroupmapping;


/** 
 * Object mapping for hibernate-handled table: groupmapping.
 * @author autogenerated
 */

@Entity
@Table(name = "groupmapping", catalog = "MoneyWizzard")
public class Groupmapping implements Cloneable, Serializable, IGroupmapping {

	/** Serial Version UID. */
	private static final long serialVersionUID = -558953631L;

	

	/** Field mapping. */
	@Id 
	private GroupmappingPK id;

	/**
	 * Default constructor, mainly for hibernate use.
	 */
	public Groupmapping() {
		// Default constructor
	} 

	/** Constructor taking a given ID.
	 * @param id to set
	 */
	public Groupmapping(GroupmappingPK id) {
		this.id = id;
	}
	
 


 
	/** Return the type of this class. Useful for when dealing with proxies.
	* @return Defining class.
	*/
	@Transient
	public Class<?> getClassType() {
		return Groupmapping.class;
	}
 

    /**
     * Return the value associated with the column: id.
	 * @return A GroupmappingPK object (this.id)
	 */
	public GroupmappingPK getId() {
		return this.id;
		
	}
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	public void setId(final GroupmappingPK id) {
		this.id = id;
	}


   /**
    * Deep copy.
	* @return cloned object
	* @throws CloneNotSupportedException on error
    */
    @Override
    public Groupmapping clone() throws CloneNotSupportedException {
		
        final Groupmapping copy = (Groupmapping)super.clone();

		copy.setId(this.getId());
		return copy;
	}
	


	/** Provides toString implementation.
	 * @see java.lang.Object#toString()
	 * @return String representation of this class.
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		
		sb.append("id: " + this.getId());
		return sb.toString();		
	}


	/** Equals implementation. 
	 * @see java.lang.Object#equals(java.lang.Object)
	 * @param aThat Object to compare with
	 * @return true/false
	 */
	@Override
	public boolean equals(final Object aThat) {
		if ( this == aThat ) {
			 return true;
		}

		if ((aThat == null) || ( !(aThat.getClass().equals(this.getClass())))) {
			 return false;
		}
	
		final Groupmapping that = (Groupmapping) aThat;
		return this.getId().equals(that.getId());
	}
	
	/** Calculate the hashcode.
	 * @see java.lang.Object#hashCode()
	 * @return a calculated number
	 */
	@Override
	public int hashCode() {
		return getId().hashCode();
	}
	

	
}
