package com.moneywizzard.model;

import java.io.Serializable;
import java.util.Arrays;
import java.util.Collections;
import java.util.Date;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.WeakHashMap;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.proxy.HibernateProxy;

import com.moneywizzard.model.iface.IGroupexpense;


/** 
 * Object mapping for hibernate-handled table: groupexpense.
 * @author autogenerated
 */

@Entity
@Table(name = "groupexpense", catalog = "MoneyWizzard")
public class Groupexpense implements Cloneable, Serializable, IGroupexpense {

	/** Serial Version UID. */
	private static final long serialVersionUID = -558953633L;

	/** Use a WeakHashMap so entries will be garbage collected once all entities 
		referring to a saved hash are garbage collected themselves. */
	private static final Map<Serializable, String> SAVED_HASHES =
		Collections.synchronizedMap(new WeakHashMap<Serializable, String>());
	
	/** hashCode temporary storage. */
	private volatile String hashCode;
	
	/** Field mapping. */
	private Date date;
	/** Field mapping. */
	private Double amount;
	/** Field mapping. */
	private String comment;
	/** Field mapping. */
	private Set<Groupexpensemapping> groupexpensemappings = new HashSet<Groupexpensemapping>();

	/** Field mapping. */
	private Group groupid;
	/** Field mapping. */
	private String id;
	/** Field mapping. */
	private Byte[] image;
	/** Field mapping. */
	private Person paidbypersonid;
	/**
	 * Default constructor, mainly for hibernate use.
	 */
	public Groupexpense() {
		// Default constructor
	} 

	/** Constructor taking a given ID.
	 * @param id to set
	 */
	public Groupexpense(String id) {
		this.id = id;
	}
	
 


 
	/** Return the type of this class. Useful for when dealing with proxies.
	* @return Defining class.
	*/
	@Transient
	public Class<?> getClassType() {
		return Groupexpense.class;
	}
 

    /**
     * Return the value associated with the column: amount.
	 * @return A Double object (this.amount)
	 */
	public Double getAmount() {
		return this.amount;
		
	}
	

  
    /**  
     * Set the value related to the column: amount.
	 * @param amount the amount value you wish to set
	 */
	public void setAmount(final Double amount) {
		this.amount = amount;
	}

    /**
     * Return the value associated with the column: comment.
	 * @return A String object (this.comment)
	 */
	@Column( length = 21845  )
	public String getComment() {
		return this.comment;
		
	}
	

  
    /**  
     * Set the value related to the column: comment.
	 * @param comment the comment value you wish to set
	 */
	public void setComment(final String comment) {
		this.comment = comment;
	}

    /**
     * Return the value associated with the column: groupexpensemapping.
	 * @return A Set&lt;Groupexpensemapping&gt; object (this.groupexpensemapping)
	 */
 	@OneToMany( fetch = FetchType.EAGER, cascade = { CascadeType.PERSIST, CascadeType.MERGE }, mappedBy = "groupexpenseid"  )
 	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@Column( nullable = false  )
	public Set<Groupexpensemapping> getGroupexpensemappings() {
		return this.groupexpensemappings;
		
	}
	
	/**
	 * Adds a bi-directional link of type Groupexpensemapping to the groupexpensemappings set.
	 * @param groupexpensemapping item to add
	 */
	public void addGroupexpensemapping(Groupexpensemapping groupexpensemapping) {
		groupexpensemapping.setGroupexpenseid(this);
		this.groupexpensemappings.add(groupexpensemapping);
	}

  
    /**  
     * Set the value related to the column: groupexpensemapping.
	 * @param groupexpensemapping the groupexpensemapping value you wish to set
	 */
	public void setGroupexpensemappings(final Set<Groupexpensemapping> groupexpensemapping) {
		this.groupexpensemappings = groupexpensemapping;
	}

    /**
     * Return the value associated with the column: groupid.
	 * @return A Group object (this.groupid)
	 */
	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@JoinColumn(name = "groupId", nullable = true )
	public Group getGroupid() {
		return this.groupid;
		
	}
	

  
    /**  
     * Set the value related to the column: groupid.
	 * @param groupid the groupid value you wish to set
	 */
	public void setGroupid(final Group groupid) {
		this.groupid = groupid;
	}

    /**
     * Return the value associated with the column: id.
	 * @return A String object (this.id)
	 */
    @Id 
	@Column( name = "groupexpenseid", nullable = false, length = 36  )
	public String getId() {
		return this.id;
		
	}
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	public void setId(final String id) {
		// If we've just been persisted and hashCode has been
		// returned then make sure other entities with this
		// ID return the already returned hash code
		if ( (this.id == null ) &&
				(id != null) &&
				(this.hashCode != null) ) {
			SAVED_HASHES.put( id, this.hashCode );
		}
		this.id = id;
	}

    /**
     * Return the value associated with the column: image.
	 * @return A Byte[] object (this.image)
	 */
	public Byte[] getImage() {
		return this.image;
		
	}
	

  
    /**  
     * Set the value related to the column: image.
	 * @param image the image value you wish to set
	 */
	public void setImage(final Byte[] image) {
		this.image = image;
	}

    /**
     * Return the value associated with the column: paidbypersonid.
	 * @return A Person object (this.paidbypersonid)
	 */
	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.EAGER )
	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@JoinColumn(name = "paidByPersonId", nullable = true )
	public Person getPaidbypersonid() {
		return this.paidbypersonid;
		
	}
	

  
    /**  
     * Set the value related to the column: paidbypersonid.
	 * @param paidbypersonid the paidbypersonid value you wish to set
	 */
	public void setPaidbypersonid(final Person paidbypersonid) {
		this.paidbypersonid = paidbypersonid;
	}

    /**
     * Return the value associated with the column: date.
	 * @return A Date object (this.date)
	 */
	public Date getDate() {
		return this.date;
		
	}
	

  
    /**  
     * Set the value related to the column: date.
	 * @param date the date value you wish to set
	 */
	public void setDate(final Date date) {
		this.date = date;
	}
   /**
    * Deep copy.
	* @return cloned object
	* @throws CloneNotSupportedException on error
    */
    @Override
    public Groupexpense clone() throws CloneNotSupportedException {
		
        final Groupexpense copy = (Groupexpense)super.clone();

		copy.setAmount(this.getAmount());
		copy.setComment(this.getComment());
		if (this.getGroupexpensemappings() != null) {
			copy.getGroupexpensemappings().addAll(this.getGroupexpensemappings());
		}
		copy.setGroupid(this.getGroupid());
		copy.setId(this.getId());
		copy.setImage(this.getImage());
		copy.setPaidbypersonid(this.getPaidbypersonid());
		return copy;
	}
	


	/** Provides toString implementation.
	 * @see java.lang.Object#toString()
	 * @return String representation of this class.
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		
		sb.append("amount: " + this.getAmount() + ", ");
		sb.append("comment: " + this.getComment() + ", ");
		sb.append("id: " + this.getId() + ", ");
		sb.append("image: " + (this.image == null ? null : Arrays.toString(this.getImage())) + ", ");
		return sb.toString();		
	}


	/** Equals implementation. 
	 * @see java.lang.Object#equals(java.lang.Object)
	 * @param aThat Object to compare with
	 * @return true/false
	 */
	@Override
	public boolean equals(final Object aThat) {
		Object proxyThat = aThat;
		
		if ( this == aThat ) {
			 return true;
		}

		
		if (aThat instanceof HibernateProxy) {
 			// narrow down the proxy to the class we are dealing with.
 			try {
				proxyThat = ((HibernateProxy) aThat).getHibernateLazyInitializer().getImplementation(); 
			} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		   	}
		}
		if (aThat == null)  {
			 return false;
		}
		
		final Groupexpense that; 
		try {
			that = (Groupexpense) proxyThat;
			if ( !(that.getClassType().equals(this.getClassType()))){
				return false;
			}
		} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		} catch (ClassCastException e) {
				return false;
		}
		
		
		boolean result = true;
		result = result && (((this.getId() == null) && ( that.getId() == null)) || (this.getId() != null  && this.getId().equals(that.getId())));
		result = result && (((getAmount() == null) && (that.getAmount() == null)) || (getAmount() != null && getAmount().equals(that.getAmount())));
		result = result && (((getComment() == null) && (that.getComment() == null)) || (getComment() != null && getComment().equals(that.getComment())));
		result = result && (((getGroupid() == null) && (that.getGroupid() == null)) || (getGroupid() != null && getGroupid().getId().equals(that.getGroupid().getId())));	
		result = result && (((getImage() == null) && (that.getImage() == null)) || (getImage() != null && getImage().equals(that.getImage())));
		result = result && (((getPaidbypersonid() == null) && (that.getPaidbypersonid() == null)) || (getPaidbypersonid() != null && getPaidbypersonid().getId().equals(that.getPaidbypersonid().getId())));	
		return result;
	}
	
	/** Calculate the hashcode.
	 * @see java.lang.Object#hashCode()
	 * @return a calculated number
	 */
	@Override
	public int hashCode() {
		if ( this.hashCode == null ) {
			synchronized ( this ) {
				if ( this.hashCode == null ) {
					String newHashCode = null;

					if ( getId() != null ) {
						newHashCode = SAVED_HASHES.get( getId() );
					}
					
					if ( newHashCode == null ) {
						if ( getId() != null ) {
							newHashCode = getId();
						} else {
						newHashCode = String.valueOf(super.hashCode());

						}
					}
					
					this.hashCode = newHashCode;
				}
			}
		}
	return this.hashCode.hashCode();
	}
	

	
}
