package com.moneywizzard.model;

import java.io.Serializable;
import java.util.Collections;
import java.util.Date;
import java.util.Map;
import java.util.WeakHashMap;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.proxy.HibernateProxy;

import com.moneywizzard.model.iface.IMwaccounthistory;


/** 
 * Object mapping for hibernate-handled table: mwaccounthistory.
 * @author autogenerated
 */

@Entity
@Table(name = "mwaccounthistory", catalog = "MoneyWizzard")
public class Mwaccounthistory implements Cloneable, Serializable, IMwaccounthistory {

	/** Serial Version UID. */
	private static final long serialVersionUID = -558953627L;

	/** Use a WeakHashMap so entries will be garbage collected once all entities 
		referring to a saved hash are garbage collected themselves. */
	private static final Map<Serializable, String> SAVED_HASHES =
		Collections.synchronizedMap(new WeakHashMap<Serializable, String>());
	
	/** hashCode temporary storage. */
	private volatile String hashCode;
	

	/** Field mapping. */
	private Double amount;
	/** Field mapping. */
	private Date date;
	/** Field mapping. */
	private String id;
	/** Field mapping. */
	private Person recieverpersonid;
	/** Field mapping. */
	private Person senderpersonid;
	/** Field mapping. */
	private String comment;
	/**
	 * Default constructor, mainly for hibernate use.
	 */
	public Mwaccounthistory() {
		// Default constructor
	} 

	/** Constructor taking a given ID.
	 * @param id to set
	 */
	public Mwaccounthistory(String id) {
		this.id = id;
	}
	
	/** Constructor taking a given ID.
	 * @param amount Double object;
	 * @param id String object;
	 */
	public Mwaccounthistory(Double amount, String id) {

		this.amount = amount;
		this.id = id;
	}
	
 


 
	/** Return the type of this class. Useful for when dealing with proxies.
	* @return Defining class.
	*/
	@Transient
	public Class<?> getClassType() {
		return Mwaccounthistory.class;
	}
 

    /**
     * Return the value associated with the column: amount.
	 * @return A Double object (this.amount)
	 */
	@Column( nullable = false  )
	public Double getAmount() {
		return this.amount;
		
	}
	

  
    /**  
     * Set the value related to the column: amount.
	 * @param amount the amount value you wish to set
	 */
	public void setAmount(final Double amount) {
		this.amount = amount;
	}

    /**
     * Return the value associated with the column: date.
	 * @return A Date object (this.date)
	 */
	public Date getDate() {
		return this.date;
		
	}
	

  
    /**  
     * Set the value related to the column: date.
	 * @param date the date value you wish to set
	 */
	public void setDate(final Date date) {
		this.date = date;
	}

    /**
     * Return the value associated with the column: id.
	 * @return A String object (this.id)
	 */
    @Id 
	@Column( name = "mwahistoryid", nullable = false, length = 36  )
	public String getId() {
		return this.id;
		
	}
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	public void setId(final String id) {
		// If we've just been persisted and hashCode has been
		// returned then make sure other entities with this
		// ID return the already returned hash code
		if ( (this.id == null ) &&
				(id != null) &&
				(this.hashCode != null) ) {
			SAVED_HASHES.put( id, this.hashCode );
		}
		this.id = id;
	}

    /**
     * Return the value associated with the column: recieverpersonid.
	 * @return A Person object (this.recieverpersonid)
	 */
	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.EAGER )
	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@JoinColumn(name = "recieverpersonId", nullable = true )
	public Person getRecieverpersonid() {
		return this.recieverpersonid;
		
	}
	

  
    /**  
     * Set the value related to the column: recieverpersonid.
	 * @param recieverpersonid the recieverpersonid value you wish to set
	 */
	public void setRecieverpersonid(final Person recieverpersonid) {
		this.recieverpersonid = recieverpersonid;
	}

    /**
     * Return the value associated with the column: senderpersonid.
	 * @return A Person object (this.senderpersonid)
	 */
	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.EAGER )
	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@JoinColumn(name = "senderpersonId", nullable = true )
	public Person getSenderpersonid() {
		return this.senderpersonid;
		
	}
	

  
    /**  
     * Set the value related to the column: senderpersonid.
	 * @param senderpersonid the senderpersonid value you wish to set
	 */
	public void setSenderpersonid(final Person senderpersonid) {
		this.senderpersonid = senderpersonid;
	}

    /**
     * Return the value associated with the column: emailid.
	 * @return A String object (this.emailid)
	 */
	@Column( nullable = false, length = 21845  )
	public String getComment() {
		return this.comment;
		
	}
	

  
    /**  
     * Set the value related to the column: emailid.
	 * @param emailid the emailid value you wish to set
	 */
	public void setComment(final String comment) {
		this.comment = comment;
	}

   /**
    * Deep copy.
	* @return cloned object
	* @throws CloneNotSupportedException on error
    */
    @Override
    public Mwaccounthistory clone() throws CloneNotSupportedException {
		
        final Mwaccounthistory copy = (Mwaccounthistory)super.clone();

		copy.setAmount(this.getAmount());
		copy.setDate(this.getDate());
		copy.setId(this.getId());
		copy.setRecieverpersonid(this.getRecieverpersonid());
		copy.setSenderpersonid(this.getSenderpersonid());
		return copy;
	}
	


	/** Provides toString implementation.
	 * @see java.lang.Object#toString()
	 * @return String representation of this class.
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		
		sb.append("amount: " + this.getAmount() + ", ");
		sb.append("date: " + this.getDate() + ", ");
		sb.append("id: " + this.getId() + ", ");
		return sb.toString();		
	}


	/** Equals implementation. 
	 * @see java.lang.Object#equals(java.lang.Object)
	 * @param aThat Object to compare with
	 * @return true/false
	 */
	@Override
	public boolean equals(final Object aThat) {
		Object proxyThat = aThat;
		
		if ( this == aThat ) {
			 return true;
		}

		
		if (aThat instanceof HibernateProxy) {
 			// narrow down the proxy to the class we are dealing with.
 			try {
				proxyThat = ((HibernateProxy) aThat).getHibernateLazyInitializer().getImplementation(); 
			} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		   	}
		}
		if (aThat == null)  {
			 return false;
		}
		
		final Mwaccounthistory that; 
		try {
			that = (Mwaccounthistory) proxyThat;
			if ( !(that.getClassType().equals(this.getClassType()))){
				return false;
			}
		} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		} catch (ClassCastException e) {
				return false;
		}
		
		
		boolean result = true;
		result = result && (((this.getId() == null) && ( that.getId() == null)) || (this.getId() != null  && this.getId().equals(that.getId())));
		result = result && (((getAmount() == null) && (that.getAmount() == null)) || (getAmount() != null && getAmount().equals(that.getAmount())));
		result = result && (((getDate() == null) && (that.getDate() == null)) || (getDate() != null && getDate().equals(that.getDate())));
		result = result && (((getRecieverpersonid() == null) && (that.getRecieverpersonid() == null)) || (getRecieverpersonid() != null && getRecieverpersonid().getId().equals(that.getRecieverpersonid().getId())));	
		result = result && (((getSenderpersonid() == null) && (that.getSenderpersonid() == null)) || (getSenderpersonid() != null && getSenderpersonid().getId().equals(that.getSenderpersonid().getId())));	
		return result;
	}
	
	/** Calculate the hashcode.
	 * @see java.lang.Object#hashCode()
	 * @return a calculated number
	 */
	@Override
	public int hashCode() {
		if ( this.hashCode == null ) {
			synchronized ( this ) {
				if ( this.hashCode == null ) {
					String newHashCode = null;

					if ( getId() != null ) {
						newHashCode = SAVED_HASHES.get( getId() );
					}
					
					if ( newHashCode == null ) {
						if ( getId() != null ) {
							newHashCode = getId();
						} else {
						newHashCode = String.valueOf(super.hashCode());

						}
					}
					
					this.hashCode = newHashCode;
				}
			}
		}
	return this.hashCode.hashCode();
	}
	

	
}
