package com.moneywizzard.dao;

import java.util.List;

import com.moneywizzard.model.Budget;
 
/**
 * DAO interface for table: Budget.
 * @author autogenerated
 */
public interface BudgetDao extends GenericDAO<Budget,  String>  {

	List<Budget> getByCriteria(Budget budget) throws Exception;
	// constructor only
}

