package com.moneywizzard.dao;

import com.moneywizzard.model.Expensecategory;
 
/**
 * DAO interface for table: Expensecategory.
 * @author autogenerated
 */
public interface ExpensecategoryDao extends GenericDAO<Expensecategory,  String>  {
	// constructor only
}

