package com.moneywizzard.dao;

import java.util.List;

import com.moneywizzard.model.Expenses;
 
/**
 * DAO interface for table: Expenses.
 * @author autogenerated
 */
public interface ExpensesDao extends GenericDAO<Expenses,  String>  {

	List<Expenses> getByCriteria(Expenses expense) throws Exception;
	// constructor only
}

