package com.moneywizzard.dao;

import java.util.List;

import com.moneywizzard.model.Friends;
import com.moneywizzard.model.FriendsPK;
/**
 * DAO interface for table: Friends.
 * @author autogenerated
 */
public interface FriendsDao extends GenericDAO<Friends,  FriendsPK>  {

	List<Friends> getByCriteria(Friends friend) throws Exception;
	// constructor only
}

