package com.moneywizzard.dao;

import java.io.Serializable;

import com.moneywizzard.model.FriendsPK;
/**
 * DAO interface for table: FriendsPK.
 * @author autogenerated
 */
public interface FriendsPKDao extends GenericDAO<FriendsPK,  Serializable>  {
	// constructor only
}

