package com.moneywizzard.dao;

import java.util.List;

import com.moneywizzard.model.Groupmapping;
import com.moneywizzard.model.GroupmappingPK;
/**
 * DAO interface for table: Groupmapping.
 * @author autogenerated
 */
public interface GroupmappingDao extends GenericDAO<Groupmapping,  GroupmappingPK>  {

	List<Groupmapping> getByCriteria(Groupmapping groupmapping) throws Exception;
	// constructor only
}

