package com.moneywizzard.dao;

import java.util.List;

import com.moneywizzard.model.Groupexpense;
 
/**
 * DAO interface for table: Groupexpense.
 * @author autogenerated
 */
public interface GroupexpenseDao extends GenericDAO<Groupexpense,  String>  {

	List<Groupexpense> getByCriteria(Groupexpense groupexpense) throws Exception;
	// constructor only
}

