package com.moneywizzard.dao;

import java.io.Serializable;

import com.moneywizzard.model.GroupmappingPK;
/**
 * DAO interface for table: GroupmappingPK.
 * @author autogenerated
 */
public interface GroupmappingPKDao extends GenericDAO<GroupmappingPK,  Serializable>  {
	// constructor only
}

