package com.moneywizzard.dao;

import com.moneywizzard.model.Group;
 
/**
 * DAO interface for table: Group.
 * @author autogenerated
 */
public interface GroupDao extends GenericDAO<Group,  String>  {
	// constructor only
}

