package com.moneywizzard.dao;

import com.moneywizzard.model.Moneywizardaccount;
import com.moneywizzard.model.Person;

/**
 * DAO interface for table: Moneywizardaccount.
 * @author autogenerated
 */
public interface MoneywizardaccountDao extends GenericDAO<Moneywizardaccount,  String>  {
	// constructor only


	Moneywizardaccount getByCriteria(Person person);
}

